name: clubedoxp
description: App do ClubedoXP

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_markdown: ^0.3.4
  cloud_firestore: ^0.12.9
  html2md: "^0.5.1"

dev_dependencies:
  flutter_launcher_icons: "^0.7.4"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logos/clubedoxp.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/images/logos/

  fonts:
  - family: OpenSans
    fonts:
      - asset: assets/fonts/OpenSans-Regular.ttf
      - asset: assets/fonts/OpenSans-Bold.ttf
        weight: 700
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat-Regular.ttf

